const testFunct = async (name: string) => {
    try {
        console.log(name)
    } catch(error){
        console.log(error)
    }
}